#!/usr/bin/env python3
"""Build the facerec app for the current platform.

macOS:   xcodebuild on the Xcode project generated by bootstrap.py
Windows: make on the msys2 makefiles (run from an MSYS2 MinGW64 shell)

The binary lands in facerec/bin/ next to the data/ folder (models etc.),
which is the runnable layout openFrameworks expects.

Usage:
  python3 scripts/build.py            build (Release)
  python3 scripts/build.py --debug    build Debug
  python3 scripts/build.py --check    build, then run the binary with
                                      --selftest and report pass/fail
  python3 scripts/build.py --run      build, then launch the app
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
APP_DIR = ROOT / "facerec"
APP_NAME = "facerec"


def log(msg):
    print(f"[build] {msg}", flush=True)


def die(msg):
    print(f"[build] ERROR: {msg}", file=sys.stderr, flush=True)
    sys.exit(1)


def build_macos(config):
    project = APP_DIR / f"{APP_NAME}.xcodeproj"
    if not project.exists():
        die(f"{project} not found — run scripts/bootstrap.py first")
    log(f"xcodebuild {config} ...")
    subprocess.run(
        ["xcodebuild", "-project", str(project), "-configuration", config,
         "-jobs", str(os.cpu_count() or 4), "build"],
        cwd=APP_DIR, check=True,
    )
    suffix = "Debug" if config == "Debug" else "Release"
    # oF's Xcode template names the bundle <target><suffix>.app in bin/
    for candidate in (APP_DIR / "bin" / f"{APP_NAME}{suffix}.app",
                      APP_DIR / "bin" / f"{APP_NAME}.app"):
        if candidate.exists():
            return candidate / "Contents" / "MacOS" / candidate.stem
    die(f"build finished but no app bundle found in {APP_DIR / 'bin'}")


def build_windows(config):
    if not shutil.which("make"):
        die("make not found — run this from an MSYS2 MinGW64 shell "
            "(fallback: generate a VS2022 project, see SCOPE.md)")
    if not (APP_DIR / "Makefile").exists():
        die("Makefile not found — run scripts/bootstrap.py first")
    log(f"make {config} ...")
    subprocess.run(
        ["make", "-j", str(os.cpu_count() or 4), config],
        cwd=APP_DIR, check=True,
    )
    exe = APP_DIR / "bin" / (f"{APP_NAME}_debug.exe" if config == "Debug" else f"{APP_NAME}.exe")
    if not exe.exists():
        die(f"build finished but {exe} not found")
    return exe


def clear_macos_quarantine(binary_path):
    # binary_path is .../<AppName>.app/Contents/MacOS/<AppName>
    app_bundle = binary_path.parents[2]
    if app_bundle.suffix != ".app":
        return
    if not shutil.which("xattr"):
        return
    result = subprocess.run(
        ["xattr", "-dr", "com.apple.quarantine", str(app_bundle)],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        log(f"cleared quarantine on {app_bundle}")
    elif "No such xattr" not in (result.stderr or ""):
        log(f"warning: could not clear quarantine on {app_bundle}: {result.stderr.strip()}")


def main():
    args = set(sys.argv[1:])
    config = "Debug" if "--debug" in args else "Release"

    if sys.platform == "darwin":
        binary = build_macos(config)
        clear_macos_quarantine(binary)
    elif sys.platform in ("win32", "cygwin", "msys"):
        binary = build_windows(config)
    else:
        die(f"unsupported platform: {sys.platform} (macOS and Windows only)")

    log(f"built {binary}")

    if "--check" in args:
        log("running self-test ...")
        result = subprocess.run([str(binary), "--selftest"], cwd=binary.parent)
        if result.returncode != 0:
            die("self-test FAILED")
        log("self-test passed")
    elif "--run" in args:
        subprocess.run([str(binary)], cwd=binary.parent)


if __name__ == "__main__":
    main()
